# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rexcel < Formula
  desc "rexcel is a tool that reads specific rows and cells from an Excel file."
  homepage "https://github.com/kaiyujin/rexcel"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaiyujin/rexcel/releases/download/v0.1.2/rexcel_Darwin_x86_64.tar.gz"
      sha256 "ede2460c09c38bfb0c42341ae6620c00d8a094de960ade2dab56b515085b058c"

      def install
        bin.install "rexcel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaiyujin/rexcel/releases/download/v0.1.2/rexcel_Darwin_arm64.tar.gz"
      sha256 "4a99373d650db525acaf439c8cb097a0d00f76cfca5bec0e994679e90d19b8ce"

      def install
        bin.install "rexcel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaiyujin/rexcel/releases/download/v0.1.2/rexcel_Linux_arm64.tar.gz"
      sha256 "663146ad21ef1eeb26349b9479ea7fb0a9cc514ba5f10941fd486a57f9597394"

      def install
        bin.install "rexcel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kaiyujin/rexcel/releases/download/v0.1.2/rexcel_Linux_x86_64.tar.gz"
      sha256 "b56c11ef7cb45b38da3918942a0748772883012231cbb1c324c6a689aa1e38e6"

      def install
        bin.install "rexcel"
      end
    end
  end
end
