# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rexcel < Formula
  desc "rexcel is a tool that reads specific rows and cells from an Excel file."
  homepage "https://github.com/kaiyujin/rexcel"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaiyujin/rexcel/releases/download/v0.1.3/rexcel_Darwin_x86_64.tar.gz"
      sha256 "27599ffa4f1146218db522bafd28c7f47cd75bcec828dcafb4e5a35714c63956"

      def install
        bin.install "rexcel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaiyujin/rexcel/releases/download/v0.1.3/rexcel_Darwin_arm64.tar.gz"
      sha256 "f3bcae053f95bc97160ad182a9049bd3085021d0897ef178af0112d4db2fbdae"

      def install
        bin.install "rexcel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kaiyujin/rexcel/releases/download/v0.1.3/rexcel_Linux_x86_64.tar.gz"
      sha256 "9da38d410a741130f2fe3e5be76b2f861e79b5835ceefb81441b6bd65091521e"

      def install
        bin.install "rexcel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaiyujin/rexcel/releases/download/v0.1.3/rexcel_Linux_arm64.tar.gz"
      sha256 "15f173b41108634d7b92225a325c28f7d82655c1ada3ef831a5f1a151c959439"

      def install
        bin.install "rexcel"
      end
    end
  end
end
